Add Form-base template for issues
eclipse-velocitas/velocitas-docs pull request #101
Opened 2023-06-26 15:15 UTC by kse3hi

## Describe your changes

## Issue ticket number and link

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

2023-06-27 12:24 UTC, dennismeister93 requested changes

2023-06-27 12:24 UTC, dennismeister93 commented on .github/ISSUE_TEMPLATE/feature-request.yml
> +  - "feature_request"
we are labeling the feature request at the moment with "enhancement"

2023-06-27 12:24 UTC, dennismeister93 commented on .github/ISSUE_TEMPLATE/feature-request.yml
> +        We kindly ask that you search to see if an issue already exists for your feature.
```suggestion
        We kindly ask you to search if an issue already exists for your requested feature.
```

2023-06-27 12:24 UTC, dennismeister93 commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      label: Additional information
```suggestion
      label: Additional Information
```

2023-06-27 12:24 UTC, dennismeister93 commented on .github/ISSUE_TEMPLATE/question.yml
> +      description: Tell us how can we help to you
```suggestion
      description: Feel free to ask us if you need assistance
```

2023-06-27 12:24 UTC, dennismeister93 commented on .github/ISSUE_TEMPLATE/question.yml
> +      placeholder: How can I create template repository?
```suggestion
      placeholder: How can I create a repository based on your template?
```

2023-06-27 13:29 UTC, kse3hi commented on .github/ISSUE_TEMPLATE/feature-request.yml
> +  - "feature_request"
shall we reconsider and change it on `feature-request`?

2023-06-28 06:49 UTC, kse3hi commented on .github/ISSUE_TEMPLATE/feature-request.yml
> +  - "feature_request"
Done

2023-06-28 15:04 UTC, dennismeister93 approved these changes
lgtm, maybe others have additional opinion

2023-06-29 06:55 UTC, MP91 requested changes

2023-06-29 06:55 UTC, MP91 commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      label: What release version,tag or hash-commit did you use?
```suggestion
      label: What release version, tag or commit-hash did you use?
```

2023-06-29 06:55 UTC, MP91 commented on .github/ISSUE_TEMPLATE/feature-request.yml
> +        We are also happy to accept contributions from our users.
```suggestion
        We are happy about contributions from all users.
```

2023-06-29 06:55 UTC, MP91 commented on .github/ISSUE_TEMPLATE/feature-request.yml
> +      required: true
Seems similar to the one above -> don't make it as required since not everybody knows how to implement

2023-06-29 06:55 UTC, MP91 commented on .github/ISSUE_TEMPLATE/feature-request.yml
> +        A clear and concise description of any alternative solutions or features you've considered.
```suggestion
        A clear and concise description of alternative solutions or features you've considered.
```

2023-06-29 06:55 UTC, MP91 commented on .github/ISSUE_TEMPLATE/feature-request.yml
> +        Describe the solution you'd like. A clear and concise description of what you want to happen.
```suggestion
        Describe the solution you'd like to be implemented. Provide a clear and concise description of what you want to happen.
```

2023-06-29 06:55 UTC, MP91 commented on .github/ISSUE_TEMPLATE/question.yml
> +name: ❓ Question
I would like to have this more generic,we have now bug and improvements and that is for everything else, so something like:
```suggestion
name: ❓ Question or general issue
```
maybe?

2023-06-29 08:05 UTC, kse3hi commented on .github/ISSUE_TEMPLATE/question.yml
> +name: ❓ Question
If we vote for "DIscussions" then we can remove this at all.

2023-06-29 08:15 UTC, MP91 commented on .github/ISSUE_TEMPLATE/question.yml
> +name: ❓ Question
hmm not really, I could imagine someone having an issue but it is not a bug or a feature request

2023-06-29 08:36 UTC, kse3hi commented on .github/ISSUE_TEMPLATE/feature-request.yml
> +      required: true
I disagree with you. If you have no idea at all, how solution can look like, then use question instead. On my opinion, it will motivate people not create useless feature requests, if they don't think a little bit about them. In worse case - they just put something like "have no idea" to pass through.

2023-06-29 08:59 UTC, MP91 commented on .github/ISSUE_TEMPLATE/feature-request.yml
> +      required: true
But what should be the difference here to the general description?

2023-06-29 09:19 UTC, kse3hi commented on .github/ISSUE_TEMPLATE/feature-request.yml
> +      required: true
It is about philosophy :) Good feature should contain from 2 parts - Description of the Problem, that feature shall solve and solution suggestion. Reference: https://featureupvote.com/blog/feature-request-template/

2023-06-30 08:46 UTC, MP91 commented on .github/ISSUE_TEMPLATE/feature-request.yml
> +      required: true
your first link also does not have this field.

@dennismeister93 what do you think, do we need this additional field as mandatory?

2023-06-30 09:04 UTC, BjoernAtBosch commented on .github/ISSUE_TEMPLATE/feature-request.yml
> +      required: true
I also agree, not to require this: If I'd like to add a feature request (and have currently no code yet - maybe because I'd like to discuss the idea before putting too much time into coding), I would expect that I can do it here and not in "questions". "Questions" are for general understanding issues (imho).

2023-06-30 09:04 UTC, BjoernAtBosch approved these changes
LGTM

2023-06-30 09:54 UTC, MP91 approved these changes
LGTM

2023-07-03 13:13 UTC, merged