Remove dapr and k3d
eclipse-velocitas/velocitas-docs pull request #119
Opened 2024-03-25 10:59 UTC by MP91

## Describe your changes

## Issue ticket number and link

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

2024-04-03 06:36 UTC, BjoernAtBosch requested changes

2024-04-03 06:36 UTC, BjoernAtBosch commented on content/en/docs/tutorials/vehicle_app_runtime/kanto_runtime.md
> +Besides starting the vehicle runtime components [locally](/docs/tutorials/vehicle_app_runtime/local_runtime), another way is to deploy them as containers using [Kanto](https://eclipse.dev/kanto/) as
I think, Kanto is not on container runtime level but on orchestration level.
```suggestion
Besides starting the vehicle runtime components [locally](/docs/tutorials/vehicle_app_runtime/local_runtime), another way is to deploy them as containers using [Kanto](https://eclipse.dev/kanto/) as a container orchestration system. To start the runtime, we provide VS Code _Tasks_, a feature of Visual Studio Code. Additional information on tasks can be found [here](https://code.visualstudio.com/docs/editor/tasks).
```

2024-04-03 06:36 UTC, BjoernAtBosch commented on content/en/docs/tutorials/vehicle_app_runtime/kanto_runtime.md
> -* Tutorial: [Start runtime services in Kubernetes](/docs/tutorials/vehicle_app_runtime/kubernetes_runtime)
Add link to Kanto runtime

2024-04-03 06:36 UTC, BjoernAtBosch commented on content/en/docs/concepts/deployment_model/_index.md
> +- The container runtime offers a control plane and API to manage the container lifecycle.
Shouldn't we mention Kanto?
```suggestion
- The container runtime offers a control plane and API base on Eclipse Kanto to manage the container lifecycle.
```

2024-04-03 06:36 UTC, BjoernAtBosch commented on content/en/docs/concepts/development_model/_index.md
> -
I wouldn't remove this section completely. Suggestion:

Velocitas basically provides middleware abstraction interfaces for service discovery, pubsub messaging, and other cross-cutting functionalites.
At the moment, Velocitas just offers a (what we call) "native middleware" implementation, which does not provide (gRPC) service discovery. Instead, addresses and port number of services need to be provided via environment variables to an app; e.g. `SDV_VEHICLEDATABROKER_ADDRESS=grpc://localhost:55555`.
The support of Dapr as middleware has recently been removed.

2024-04-03 10:05 UTC, MP91 commented on content/en/docs/concepts/deployment_model/_index.md
> +- The container runtime offers a control plane and API to manage the container lifecycle.
we also have the "Local runtime" which is basically docker based... So in general we can deploy everywhere where OCI compliant containers are supported. Therefore I would not add Kanto here.

2024-04-03 10:15 UTC, MP91 commented on content/en/docs/tutorials/vehicle_app_runtime/kanto_runtime.md
> -* Tutorial: [Start runtime services in Kubernetes](/docs/tutorials/vehicle_app_runtime/kubernetes_runtime)
this would link to the same page...

2024-04-03 10:19 UTC, MP91 commented on content/en/docs/tutorials/vehicle_app_runtime/kanto_runtime.md
> +Besides starting the vehicle runtime components [locally](/docs/tutorials/vehicle_app_runtime/local_runtime), another way is to deploy them as containers using [Kanto](https://eclipse.dev/kanto/) as
hmm you might be right, but if we change this now, we have to change it everywhere. But what is the definition of a runtime? Is Docker a runtime? 

I would like to keep this like it is for now...

2024-04-03 10:21 UTC, BjoernAtBosch commented on content/en/docs/tutorials/vehicle_app_runtime/kanto_runtime.md
> -* Tutorial: [Start runtime services in Kubernetes](/docs/tutorials/vehicle_app_runtime/kubernetes_runtime)
Oops - didn't recognize :-"

2024-04-03 10:27 UTC, BjoernAtBosch commented on content/en/docs/concepts/deployment_model/_index.md
> +- The container runtime offers a control plane and API to manage the container lifecycle.
But what is the "API" in that case?

2024-04-04 10:51 UTC, BjoernAtBosch approved these changes
LGTM

2024-04-04 10:56 UTC, merged