Update vehicle-signal-interface configuration options
eclipse-velocitas/velocitas-docs pull request #122
Opened 2024-05-06 11:56 UTC by lukasmittag

## Describe your changes

## Issue ticket number and link

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

2024-05-06 12:24 UTC, erikbosch commented on content/en/docs/concepts/development_model/vehicle_app_manifest/interfaces/vehicle_signal_interface.md
> +| `unit_src` | string | ["abs_path_unit_file_1", "abs_path_unit_file_2", "uri_unit_file_3"] | An array of URI's/absolute path's of the used COVESA Vehicle Signal Specification unit file(s) in yaml fo
Should we write the argument "as code", like:
```
 `["abs_path_unit_file_1", "abs_path_unit_file_2", "uri_unit_file_3"]`
```

2024-05-07 07:54 UTC, dennismeister93 requested changes

2024-05-07 07:54 UTC, dennismeister93 commented on content/en/docs/concepts/development_model/vehicle_app_manifest/interfaces/vehicle_signal_interface.md
Could you write a bit (doesn't need to be much) about v3 + v4 support and also something with the difference of the configuration of the mock-service/mock.py?

2024-06-07 11:11 UTC, dennismeister93 approved these changes

2024-06-07 11:12 UTC, merged