Describe signal error handling
eclipse-velocitas/velocitas-docs pull request #124
Opened 2024-05-30 12:13 UTC by BjoernAtBosch

## Describe your changes

## Issue ticket number and link

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

2024-05-30 14:17 UTC, dennismeister93 requested changes

2024-05-30 14:17 UTC, dennismeister93 commented on content/en/docs/tutorials/vehicle_app_development/cpp_development.md
> +In order to facilitate the implementation, the whole set of vehicle signal is abstracted into model classes. Please check the [tutorial about creating models](/docs/tutorials/vehicle_model_creation)
```suggestion
In order to facilitate the implementation, the whole set of vehicle signals is abstracted into model classes. Please check the [tutorial about creating models](/docs/tutorials/vehicle_model_creation) for more details. In this section, the focus is on using the model.
```

2024-05-30 14:17 UTC, dennismeister93 commented on content/en/docs/tutorials/vehicle_app_development/cpp_development.md
> +The first thing you need to do is to get access to the Vehicle Model. If you derived your project repository from our template, we already provide a generated model as a Conan source package. The lib
```suggestion
The first thing you need to do is to get access to the Vehicle Model. If you derived your project repository from our template, we already provide a generated model as a Conan source package. The library is already referenced as "include folder" in the CMake files. Hence, in most cases no additional setup is necessary. How to tailor the model to your needs or how you could get access to vehicle services is described in the tutorial linked above. In your source code the model is included via `#include "vehicle/Vehicle.hpp"` (as shown above).
```

2024-05-30 14:17 UTC, dennismeister93 commented on content/en/docs/tutorials/vehicle_app_development/cpp_development.md
> +  Behind the scenes this triggers an request-response flow via IPC with the Data Broker.
```suggestion
  Behind the scenes this triggers a request-response flow via IPC with the Data Broker.
```

2024-05-30 14:17 UTC, dennismeister93 commented on content/en/docs/tutorials/vehicle_app_development/cpp_development.md
> +* The term `->await()` causes the executiom to block until the response was received.
```suggestion
* The term `->await()` causes the execution to block until the response is received.
```

2024-05-30 14:17 UTC, dennismeister93 commented on content/en/docs/tutorials/vehicle_app_development/cpp_development.md
> +If you have a detailed look at the `AsyncResult` class, you will observe that the object returned by the `await()` or passed to the `onResult` callback is not directly the current value of the signal
```suggestion
If you have a detailed look at the `AsyncResult` class, you will observe that the object returned by the `await()` or passed to the `onResult` callback is not directly the current value of the signal, but instead an object of type `TypedDataPointValue`. This object does not only contain the current value of the signal but also some additional metadata accessible via these functions:
```

2024-05-30 14:17 UTC, dennismeister93 commented on content/en/docs/tutorials/vehicle_app_development/cpp_development.md
> +* `isValid()` returns `true` if the current state repesents a valid value of the signal or `false` otherwise,
```suggestion
* `isValid()` returns `true` if the current state represents a valid value of the signal or `false` otherwise,
```

2024-05-30 14:17 UTC, dennismeister93 commented on content/en/docs/tutorials/vehicle_app_development/cpp_development.md
> +* The value of is missing because of some internal issue in the data broker (`Failure::INTERNAL_ERROR`). This typically points out some misbehaviour within the broker's implementation - call it "bug"
```suggestion
* The value is missing because of some internal issue in the data broker (`Failure::INTERNAL_ERROR`). This typically points out some misbehaviour within the broker's implementation - call it "bug".
```

2024-05-30 14:17 UTC, dennismeister93 commented on content/en/docs/tutorials/vehicle_app_development/cpp_development.md
> +The result passed to the callback registered via `onItem()` is an object of type `DataPointsResult` which holds the current state of all data points that were part if the respective subscription. The
```suggestion
The result passed to the callback registered via `onItem()` is an object of type `DataPointsResult` which holds the current state of all data points that were part of the respective subscription. The state of individual data points can be accessed by their reference: `result.get(Vehicle.Cabin.Seat.Row1.Pos1.Position)`)
```

2024-05-30 14:17 UTC, dennismeister93 commented on content/en/docs/tutorials/vehicle_app_development/cpp_development.md
> +If you select multiple signals/data pints in a single subscription be aware that:
```suggestion
If you select multiple signals/data points in a single subscription be aware that:
```

2024-05-30 14:17 UTC, dennismeister93 commented on content/en/docs/tutorials/vehicle_app_development/cpp_development.md
> +1. The update notification will not only contain those data points whose states were updated, but the state of all data points selected in the belonging subscription. If you don't want this behaviour
```suggestion
1. The update notification will not only contain those data points whose states were updated, but the state of all data points selected in the belonging subscription. If you don't want this behaviour, you must subscribe to change notifications for each signal/data point separately.
```

2024-05-30 14:17 UTC, dennismeister93 commented on content/en/docs/tutorials/vehicle_app_development/cpp_development.md
> +2. A possible failure state will be reported individually per signal/data point. The reason is, that each signal/data point might come from a different provider, has individual access rights, and ind
```suggestion
2. A possible failure state will be reported individually per signal/data point. The reason is, that each signal/data point might come from a different provider, has individual access rights and individual reasons to become invalid. This is also true, if requesting multiple signal/data point states via a single get call.
```

2024-05-30 14:20 UTC, doosuu requested changes

2024-05-30 14:20 UTC, doosuu commented on content/en/docs/tutorials/vehicle_app_development/cpp_development.md
> +If you have a detailed look at the `AsyncResult` class, you will observe that the object returned by the `await()` or passed to the `onResult` callback is not directly the current value of the signal
```suggestion
If you have a detailed look at the `AsyncResult` class, you will observe that the object returned by the `await()` or passed to the `onResult` callback is not directly the current value of the signal, but instead an object of type `TypedDataPointValue`. This object does not only contain the current value of the signal but also some additional metadata accessible via these functions:
```

2024-05-30 14:20 UTC, doosuu commented on content/en/docs/tutorials/vehicle_app_development/cpp_development.md
> +The first thing you need to do is to get access to the Vehicle Model. If you derived your project repository from our template, we already provide a generated model #TODO# in the folder `app/vehicle_
```suggestion
The first thing you need to do is to get access to the Vehicle Model. If you derived your project repository from our template, a model has already been auto-generated and converted into a local [Conan](https://conan.io) package. This package has already been auto-added to the `conanfile.txt` by the tooling. Hence, in most cases no additional setup is necessary. How to tailor the model to your needs or how you could get access to vehicle services is described in the tutorial linked above.
```

2024-05-30 14:20 UTC, doosuu commented on content/en/docs/tutorials/vehicle_app_development/cpp_development.md
> +The latter three points lead us to
```suggestion
The latter three points lead us to the next chapter.
```

2024-05-30 14:20 UTC, doosuu commented on content/en/docs/tutorials/vehicle_app_development/cpp_development.md
> +It is the application implementer's decision if it makes sense to distinguish between the different failure reasons or if some or all of them can be handled as "just one".
```suggestion
It is the application developer's decision if it makes sense to distinguish between the different failure reasons or if some or all of them can be handled as "just one".
```

2024-05-31 08:39 UTC, doosuu commented on content/en/docs/tutorials/vehicle_app_development/cpp_development.md
> +* Throwing the `InvalidValueException`can be avoided if you first check that `.isValid()` returns true before calling `.value()`:
```suggestion
* Throwing the `InvalidValueException` can be avoided if you first check that `.isValid()` returns true before calling `.value()`: 
```

2024-05-31 08:58 UTC, doosuu approved these changes
lgtm

2024-05-31 09:36 UTC, merged