Add tutorial and docs for grpc interface
eclipse-velocitas/velocitas-docs pull request #127
Opened 2024-06-07 10:02 UTC by lukasmittag

## Describe your changes

## Issue ticket number and link

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [x] Do we need to implement analytics?
- [x] Will this be part of a product update? If yes, please write one phrase about this update.

2024-06-07 11:01 UTC, doosuu requested changes

2024-06-07 11:01 UTC, doosuu commented on content/en/docs/tutorials/grpc_service_generation/_index.md
> +    velocitas::VehicleModelContext::getInstance().setVdbc(
This should only be sent once in `main.cpp` we do not want to create instances of VDBClients multiple times.

2024-06-07 11:11 UTC, lukasmittag commented on content/en/docs/tutorials/grpc_service_generation/_index.md
> +  ./build/bin/server
true, I've extended the cmake file. Should we just tell them how to run one thing or maybe give them the cmake file as well?

2024-06-10 14:04 UTC, doosuu requested changes

2024-06-10 14:04 UTC, doosuu commented on content/en/docs/tutorials/grpc_service_generation/example.md
> +    auto             seat          = response->mutable_seat();
Why do you use `mutable_seat` and `mutable_position` here? These are only useful if you want to modify the content of the request. Please use the non mutable ones instead.

2024-06-10 14:04 UTC, doosuu commented on content/en/docs/tutorials/grpc_service_generation/example.md
> +    seat_position->set_base(seatPos);
You need to set something in the `response` object, not the `request` object.

2024-06-10 14:04 UTC, doosuu commented on content/en/docs/tutorials/grpc_service_generation/example.md
> +    // you would need to extend this to add support for lumbar etc.
`response` should be filled at least with the bare minimum information

2024-06-10 14:17 UTC, lukasmittag commented on content/en/docs/tutorials/grpc_service_generation/example.md
> +    auto             seat          = response->mutable_seat();
because there is no `set_position` only a `set_allocated_position`. The constructor adds a seat to the resposne object. If we get the mutable ones we can just change them and do not need to allocate our own seat object (that gets freed before accessing it on the client side -> invalid pointer error).

2024-06-10 17:57 UTC, doosuu commented on content/en/docs/tutorials/grpc_service_generation/example.md
> +    auto             seat          = response->mutable_seat();
Ok my bad. read this as `request` rather than `response`. All good!

2024-06-11 09:42 UTC, lukasmittag commented on content/en/docs/tutorials/grpc_service_generation/example.md
> +    // you would need to extend this to add support for lumbar etc.
`MoveReply` is empty defined so not fillable :)

2024-06-12 04:52 UTC, doosuu requested changes

2024-06-12 04:52 UTC, doosuu commented on content/en/docs/tutorials/grpc_service_generation/_index.md
> +To create a client we use the generated `SeatsServiceClientFactory.h` and `seats.grpc.pb.h`. These define request and resposne types and the operations that are available. An example implementation f
```suggestion
To create a client we use the generated `SeatsServiceClientFactory.h` and `seats.grpc.pb.h`. These define request and response types and the operations that are available. An example implementation for the SeatService follows:
```

2024-06-12 04:52 UTC, doosuu commented on content/en/docs/tutorials/grpc_service_generation/_index.md
> +    return 1;
Superfluous return, if / else is already exhaustive

2024-06-12 04:52 UTC, doosuu commented on content/en/docs/tutorials/grpc_service_generation/_index.md
> +    velocitas::VehicleModelContext::getInstance().setVdbc(
Might be a good idea to set the vdbc before instantiating the server - in case someone accesses the Vehicle Model during server setup

2024-06-12 05:16 UTC, doosuu commented on content/en/docs/tutorials/grpc_service_generation/_index.md
> +{{% tab header="Create a client" %}}
Just had a look at the rendered output - putting the entire content in a tab looks wrong and code blocks do not pop out as good as they should. I suggest we switch to 2 individual markdown files for server and client creation and just link them here.

2024-06-12 07:08 UTC, doosuu commented on content/en/docs/tutorials/grpc_service_generation/_index.md
> +Have a look at the other tabs for a tutorial how it would be done for a SeatService leveraging <https://raw.githubusercontent.com/eclipse-kuksa/kuksa-incubation/main/seat_service/proto/sdv/edge/comfo
We are not using tabs anymore ;-)

2024-06-12 07:12 UTC, doosuu commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +#include "sdk/VehicleApp.h"
Sorry I only see this now: In the C++ SDK and template we generally use double quotes for includes from the same project (i.e. the local file tree) all includes coming from software dependencies are wrapped in <> instead. Therefore we should adjust it here as well -> only SeatsServiceImpl.h should stay in double quotes.

2024-06-12 07:37 UTC, doosuu approved these changes
lgtm

2024-06-12 08:00 UTC, doosuu approved these changes
lgtm

2024-06-12 08:42 UTC, merged

2024-09-11 09:58 UTC, erikbosch commented
Note that this not yet in deployed to https://eclipse-velocitas.github.io/velocitas-docs/docs/concepts/development_model/vehicle_app_manifest/interfaces/grpc_interface/, as that does not happen automatically