Improve service documentation
eclipse-velocitas/velocitas-docs pull request #129
Opened 2024-10-22 15:31 UTC by erikbosch

## Describe your changes

## Issue ticket number and link

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

2024-10-23 12:02 UTC, MP91 requested changes
please check if you could move some general concepts to the title page to not copy'n'paste the same content on 2 pages. The definition of address/port comes to my mind e.g.

2024-10-23 12:02 UTC, MP91 commented on README.md
> +`/usr/bin/hugo server -D -s .`
one could simply use the provided devcontainer

2024-10-23 12:02 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/_index.md
> +to use the host network, and for the server `forwardPorts": [ 5555 ]` were used to forward port 5555.
```suggestion
For this to work the `.devcontainer/devcontainer.json` was changed. In the setup `--network=host` was added to allow the containers to use the host network, and for the server `forwardPorts": [ 5555 ]` was used to forward port 5555.
```

2024-10-23 12:02 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/_index.md
> +* With a Databroker Client ([Kuksa Python Client](https://pypi.org/project/kuksa-client/) or [Databroker CLI](https://github.com/eclipse-kuksa/kuksa-databroker)) set the current value of `Vehicle.Cab
```suggestion
* Set the current value of `Vehicle.Cabin.Seat.Row1.DriverSide.Position` to a valid value, for example 12, using a Databroker Client ([Kuksa Python Client](https://pypi.org/project/kuksa-client/) or [Databroker CLI](https://github.com/eclipse-kuksa/kuksa-databroker))
```

2024-10-23 12:02 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/_index.md
> +* Using the Databroker Client, verify that the target value of `Vehicle.Cabin.Seat.Row1.DriverSide.Position` has been set to 75.
```suggestion
* Use the Databroker Client to verify that the target value of `Vehicle.Cabin.Seat.Row1.DriverSide.Position` has been set to 75.
```

2024-10-23 12:02 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_client.md
> +and now you want to modify it to act as a client.
```suggestion
This example assumes that you have used the [Velocitas App C++ Template](https://github.com/eclipse-velocitas/vehicle-app-cpp-template) to create a new repository and now want to modify it to be a grpc service client.
```

2024-10-23 12:02 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_client.md
> +In the `AppManifest.json` file you need to specify which interfaces your App want to use or provide.
```suggestion
In the `AppManifest.json` file you need to specify which interfaces your App wants to use or provide.
```

2024-10-23 12:02 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_client.md
> +In this case it declares that it want to use `Move` and `CurrentPosition` from the Seats service defined in `seats.proto`.
```suggestion
In this case it declares that it wants to use `Move` and `CurrentPosition` from the Seats service defined in `seats.proto`.
```

2024-10-23 12:02 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_client.md
> +but the SDK has been updated in the background so you can use it in the file containing `main()`.
One could also use the task to generate the grpc sdks

2024-10-23 12:02 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_client.md
> +You need to add `Launcher.cpp` to `src/CMakeLists.txt`.
In the current template we already have the Launcher.cpp available

2024-10-23 12:02 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_client.md
> +include <sdk/middleware/Middleware.h>
```suggestion
#include <sdk/middleware/Middleware.h>
```

2024-10-23 12:02 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_client.md
> +        if (status.error_code() == ::grpc::StatusCode::OK)
I think there is something simpler like
```suggestion
        if (status.ok())
```

2024-10-23 12:02 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_client.md
> +server.
```suggestion
As preparation for running you must also set two environment variables to define the address/port of the server.
```

2024-10-23 12:02 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +and now you want to modify it to act as a client.
see above + it should act as a server not client

2024-10-23 12:02 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +In the `AppManifest.json` file you need to specify which interfaces your App want to use or provide.
```suggestion
In the `AppManifest.json` file you need to specify which interfaces your server will provide.
```

2024-10-23 12:02 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +and that it want write access to the VSS signal `Vehicle.Cabin.Seat.Row1.DriverSide.Position`.
```suggestion
In this case it declares to implement everything from the Seats service defined in `seats.proto` and that it needs write access to the VSS signal `Vehicle.Cabin.Seat.Row1.DriverSide.Position`.
```

2024-10-23 12:02 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +                "provided": { }
don't you need to fill the array with the actual method names?

2024-10-23 12:02 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +They contain the stub for the server. You need to fill in the actual implementation of the services.
```suggestion
They contain the stubs for the server. You still need to fill in the actual implementation of the services.
```

2024-10-23 12:02 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +The example also show basic error handling.
```suggestion
The example also shows basic error handling.
```

2024-10-23 12:02 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +just forward the request to the Databroker and return the result.
```suggestion
The business logic of the server is to wait for `Move` and `CurrentPosition` requests and when received just forward the request to the Databroker and return the result.
```

2024-10-23 12:02 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +as the header includes the *.cpp file and th header file will be included from `Launcher.cpp`.
```suggestion
You do not need to add `SeatsServiceImpl.cpp` to `src/CMakeLists.txt` as the header includes the *.cpp file and the header file will be included in the `Launcher.cpp`.
```

2024-10-23 12:02 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +            m_vehicleModel->Cabin.Seat.Row1.DriverSide.Position.set(seat.position().base())
why do you use that m_vehicleModel and not the standard Vehicle?

2024-10-23 12:02 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +You need to add `Launcher.cpp` to `src/CMakeLists.txt`.
as above in our standard template it is already there

2024-10-23 12:02 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +server and the Databroker.
see above

2024-10-23 12:02 UTC, MP91 commented on examples/README.md
> +- To simplify maintenance and updates of the examples as needed.
normally this should not be needed at all.
the reader will barely directly come to this repository but only read the rendered documentation online. furthermore most of the code is already available in the other repositories, if not we should better provide the correct inline code and explanation how and where to add it.

2024-10-24 09:24 UTC, erikbosch commented on README.md
> +`/usr/bin/hugo server -D -s .`
I will try that out and if it works document it,even if I do not really agree on the "simple" part, after all it takes some time to build/connect to the devcontainer

2024-10-24 12:15 UTC, erikbosch commented on README.md
> +`/usr/bin/hugo server -D -s .`
Works after some fixes. Will add some text on that as well

2024-10-24 13:16 UTC, erikbosch commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +                "provided": { }
Does not seem to be needed.

From the documentation at https://eclipse.dev/velocitas/docs/concepts/development_model/vehicle_app_manifest/interfaces/grpc_interface/#configuration-structure it actually seems that you cannot even give more detailed information.

Here I do not know how GRPC works. By default today we generate all methods returning `UNIMPLEMENTED`.
Does gRPC (C++ code) accepts that some bodies are missing? I assume we could adapt the generation so that if you list only method A out of A-C, then empty methods for B-C that return `UNIMPLEMENTED` would be hidden somewhere inside the SDK, but I do not know if that really would be beneficial.

2024-10-24 13:33 UTC, erikbosch commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +            m_vehicleModel->Cabin.Seat.Row1.DriverSide.Position.set(seat.position().base())
It depends on what we mean with `standard`. This is the approach we use in:

https://github.com/eclipse-velocitas/vehicle-app-cpp-sdk/blob/main/examples/seat-adjuster/src/SeatAdjusterApp.h#L75

I did some testing forward and backward, I think I can use the other approach, will do a sanity check

2024-10-24 15:07 UTC, erikbosch commented on examples/README.md
> +- To simplify maintenance and updates of the examples as needed.
I add this primarily for committers/contributors, to make it easier to verify if the examples are still runnable as presented in *.md files. Like if in about 6 months wants to check that example still is correct, I can easily copy the files to my own devcontainer setup and check that the client/server starts as expected.

One can argue that we just could recreate the files by copying the snippets from the *.md files but that would be somewhat more cumbersome as I see it. 

I had some thoughts if we should add the examples to the cpp-sdk repo, but then they might become out of sync.

2024-10-24 15:20 UTC, erikbosch commented
> please check if you could move some general concepts to the title page to not copy'n'paste the same content on 2 pages. The definition of address/port comes to my mind e.g.

I wanted to let

> please check if you could move some general concepts to the title page to not copy'n'paste the same content on 2 pages. The definition of address/port comes to my mind e.g.

I think it has a value that the client/server pages are quite independent, and the environment variables you need to set varies partially.

2024-10-25 04:42 UTC, MP91 commented on examples/README.md
> +- To simplify maintenance and updates of the examples as needed.
Got your point, on the other hand I think the surroundings in the examples change more often than the actual code (e.g. imports, package versions, velocitas features). Resulting in additional maintenance effort to keep the examples running. 
So in principle it's a good idea but in our case determined to fail IMO

2024-10-25 04:45 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +                "provided": { }
yeah should be possible to only generate the stubs which are actually needed, but if it is working like this it is fine for now. let us only document what is currently there and not add additional features :)

2024-10-25 06:32 UTC, MP91 requested changes

2024-10-25 06:32 UTC, MP91 commented on .devcontainer/Dockerfile
> +    echo Wanted Architecture is ${ARCH} && \
It is not the wanted architecture but the actual architecture of your machine

2024-10-25 06:32 UTC, MP91 commented on .devcontainer/scripts/postCreateCommand.sh
> +hugo mod get -u github.com/google/docsy@v0.11.0
with these changes we should be careful. It happened already that the whole design was broken due to an update. did you check if the site is still buildable and looking good?

2024-10-25 06:32 UTC, MP91 commented on .github/workflows/ci.yml
> -      - "main"
we don't actually want to build it on every push to every branch. please change it to pushes on main and prs opened targeting main

2024-10-25 06:32 UTC, MP91 commented on .github/workflows/ci.yml
> +          docker buildx build -f Dockerfile -t test:latest .
why not using the devcontainer ci? see https://github.com/eclipse-velocitas/vehicle-app-python-template/blob/5f2e678a86e909b2e9e583a2205c985a8b9fdf6b/.github/workflows/check-devcontainer.yml#L38 for an example. This is building the devcontainer and than running the specified commands inside of it

2024-10-25 06:32 UTC, MP91 commented on .github/workflows/ci.yml
> +        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
should be adapted if you change the trigger

2024-10-25 06:32 UTC, MP91 commented on README.md
> +This will result in that `go.mod`and `go.sum` gets updated.
```suggestion
To upgrade you need to change the docsy version in [postCreateCommand.sh](.devcontainer/scripts/postCreateCommand.sh) and rebuild the devcontainer.
This will result in updated versions of `go.mod`and `go.sum`.
```

2024-10-25 06:32 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/_index.md
> +The setup used for the examples have been as followed:
```suggestion
The following setup was used for the examples:
```

2024-10-25 06:32 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/_index.md
> +and for the server `forwardPorts": [ 5555 ]` was used to forward port 5555.
```suggestion
In the setup `--network=host` was added to allow the containers to use the host network. 
For the server `forwardPorts": [ 5555 ]` was additionally used to forward port 5555.
```

2024-10-25 06:32 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/_index.md
> +Note that changes to `.devcontainer/devcontainer.json` may be overwritten when `velocitas sync`is performed.
```suggestion
Note that changes to `.devcontainer/devcontainer.json` may be overwritten when `velocitas sync` is performed.
```

2024-10-25 06:32 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/_index.md
> +To run the examples the following actions needs to be performed in the following order:
```suggestion
To run the examples the following actions need to be performed in the shown order:
```

2024-10-25 06:32 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/_index.md
> +  If using a Databroker on host make sure that it is compatible with the Velocitas version you are using
```suggestion
  If using a Databroker on host, make sure that it is compatible with the Velocitas version you are using.
```

2024-10-25 06:32 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/_index.md
> +  The catalog used must also be compatible with the signals used in the example
```suggestion
  The catalog used must also be compatible with the signals used in the example.
```

2024-10-25 06:32 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_client.md
> +Dependning on how you intend to deploy the Application and Databroker the number of Velocitas components required varies.
```suggestion
Depending on how you intend to deploy the Application and Databroker the number of Velocitas components required varies.
```

2024-10-25 06:32 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_client.md
> +in this example we modify the file `Launcher.cpp` that already exist in the [template](https://github.com/eclipse-velocitas/vehicle-app-cpp-template).
```suggestion
You need to have a file that implements the client behavior.
In this example we modify the file `Launcher.cpp` that already exist in the [template](https://github.com/eclipse-velocitas/vehicle-app-cpp-template).
```

2024-10-25 06:32 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_client.md
> +As preparation for running you must also set an environment variables to define the address/port of the server.
```suggestion
As preparation for running the client you must also set an environment variable to define the address/port of the server.
```

2024-10-25 06:32 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_client.md
> +As preparation for running you must also set an environment variables to define the address/port of the server.
please also add a note that you have to start the client in the same terminal, otherwise the env gets lost

2024-10-25 06:32 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_client.md
> +If Databroker and the Server is running and has a current value for the wanted signal, then everthing shall work when the client is started.
```suggestion
If Databroker and the Server are running and have a valid value for the wanted signal, everything should work when the client is started.
```

2024-10-25 06:32 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +This example assumes that you have used the [Velocitas App C++ Template](https://github.com/eclipse-velocitas/vehicle-app-cpp-template) to create a new repository and now want to modify it to be a gr
```suggestion
This example assumes that you have used the [Velocitas App C++ Template](https://github.com/eclipse-velocitas/vehicle-app-cpp-template) to create a new repository and now want to modify it to be a grpc service server.
```

2024-10-25 06:32 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +In the `AppManifest.json` file you need to specify which interfaces your server will provide.
This line is not true, since we only have to specify that we are a provider in general.

2024-10-25 06:32 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +In the `AppManifest.json` file you need to specify which interfaces your server will provide.
```suggestion
In the `AppManifest.json` you need to specify that your server will provide the interfaces defined in the proto file.
```

2024-10-25 06:32 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +If it require access to signals in Databroker it must also be specified.
```suggestion
If it requires access to signals from the Databroker, they must also be specified.
```

2024-10-25 06:32 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +In this case it declares to implement everything from the Seats service defined in `seats.proto` and that it needs write access to the VSS signal `Vehicle.Cabin.Seat.Row1.DriverSide.Position`.
```suggestion
In this example the server declares to provide the interfaces from the Seats service defined in `seats.proto` and that it needs write access to the VSS signal `Vehicle.Cabin.Seat.Row1.DriverSide.Position`.
```

2024-10-25 06:32 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +            m_vehicleModel->Cabin.Seat.Row1.DriverSide.Position.set(seat.position().base())
I was more referring to our templates like here: https://github.com/eclipse-velocitas/vehicle-app-python-template/blob/5f2e678a86e909b2e9e583a2205c985a8b9fdf6b/app/src/main.py#L66

But also see now that we don't inherit from the sdks base vehicleapp...

2024-10-25 06:32 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +to the file `SeatsServiceImpl.h`
```suggestion
The service will access the vehicle model, in this tutorial we manage that by adding a private class variable `vehicle` to the file `SeatsServiceImpl.h`
```

You also need to adapt the constructor to be able to pass the vehicle object, otherwise it is currently not initialized in the example as far as I can see.

2024-10-25 06:32 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +            vehicle.Cabin.Seat.Row1.DriverSide.Position.set(seat.position().base())->await();
don't you need to set it the position to a specific value?

2024-10-25 06:32 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +    auto seatServer = SeatsServiceServerFactory::create(Middleware::getInstance(), seatsImpl);
here you need to pass the vehicle to the server

2024-10-25 06:32 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +server and the Databroker.
```suggestion
As preparation for running you must also set two environment variables to define where the address/port of the server and the Databroker.
```

please also add a note to start the server in the same terminal

2024-10-25 07:00 UTC, erikbosch commented on .devcontainer/Dockerfile
> +    echo Wanted Architecture is ${ARCH} && \
It is the architecture that we want to use in the download, but I get your point

2024-10-25 07:01 UTC, erikbosch commented on .devcontainer/Dockerfile
> +    echo Wanted Architecture is ${ARCH} && \
And the terms used by Hugo does not really say what architecture it is without knowing "hugo lingo", like it is not obvious that `64bit` indicates AMD.

2024-10-25 07:09 UTC, erikbosch commented on .devcontainer/scripts/postCreateCommand.sh
> +hugo mod get -u github.com/google/docsy@v0.11.0
Yes. 

Do you have any other suggestion? The error you got when trying to start hugo in dev container is because the current docsy theme uses obsolete settings. So the alternative is to start using an older Hugo version I assume. (We currently always use latest and greatest hugo, causing the regression in the devcontainer)

2024-10-25 07:13 UTC, MP91 commented on .devcontainer/scripts/postCreateCommand.sh
> +hugo mod get -u github.com/google/docsy@v0.11.0
I'm absolutely no expert in web development so my suggestion in such cases was always to ask @dennismeister93  for help. maybe he can spare some time to advise us

2024-10-25 08:21 UTC, erikbosch commented on .github/workflows/ci.yml
> +          docker buildx build -f Dockerfile -t test:latest .
Works if we run hugo server (started in poststartcommand) in background, otherwise it just hangs waiting for it to finish

2024-10-25 08:53 UTC, erikbosch commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +In the `AppManifest.json` file you need to specify which interfaces your server will provide.
Really?

In the JSON file you need specify a list of explicit proto interfaces, right? It is not sufficient to say that we are a generic proto provider.

2024-10-25 09:04 UTC, erikbosch commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +to the file `SeatsServiceImpl.h`
It is a class variable (not a pointer), so initialized automatically when class  initialized, same construct like in https://github.com/eclipse-velocitas/vehicle-app-cpp-template/blob/main/app/src/SampleApp.h and https://github.com/eclipse-velocitas/vehicle-app-cpp-template/blob/main/app/src/SampleApp.cpp, or?

2024-10-25 09:07 UTC, erikbosch commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +            vehicle.Cabin.Seat.Row1.DriverSide.Position.set(seat.position().base())->await();
The client sets it to 75, the server sets it to the value it receives from the client.

I have not really tried to change the business logic of the "old" example, it should have the same features as before, even if they do not really makes sense always.

2024-10-25 09:11 UTC, erikbosch commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +    auto seatServer = SeatsServiceServerFactory::create(Middleware::getInstance(), seatsImpl);
We can actually remove the `vehicle` variable a few lines above as we have a private class variable (not pointer) in the server class, just like in https://github.com/eclipse-velocitas/vehicle-app-cpp-template/blob/main/app/src/SampleApp.h

2024-10-25 09:13 UTC, erikbosch commented on examples/README.md
> +- To simplify maintenance and updates of the examples as needed.
Well, it didn't work that well before either when we didn't have any files, the snippets in the *.md were not possible to compile. I suggest we keep them, if you want to remove them I suggest we take it up for discussion at the next velocitas architecture/committer round.

2024-10-25 09:19 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +In the `AppManifest.json` file you need to specify which interfaces your server will provide.
since the provide array is empty it does not directly say which interfaces it provides, we just say please generate the provider in general

2024-10-25 09:25 UTC, erikbosch commented on .devcontainer/scripts/postCreateCommand.sh
> +hugo mod get -u github.com/google/docsy@v0.11.0
We should anyway better have a test instruction or test setup, like what should someone check before they trigger the `Publish Documentation` workflow. I will add an embryo in the README that could be improved later.

2024-10-25 09:26 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +to the file `SeatsServiceImpl.h`
hmm yes you are right, I was thinking of another example we developed and there we had used and started several clients and service in one method. there it was better to pass the reference to the model instead of always initializing a new model.
But for this example it should be fine

2024-10-25 09:28 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +            vehicle.Cabin.Seat.Row1.DriverSide.Position.set(seat.position().base())->await();
ah Github collapsed the lines where the seat was constructed from the request, sorry. should be fine

2024-10-25 09:29 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +    auto seatServer = SeatsServiceServerFactory::create(Middleware::getInstance(), seatsImpl);
see my other comment, for this example it is enough to initialize a new model

2024-10-25 09:37 UTC, erikbosch commented on .devcontainer/Dockerfile
>  RUN apt-get update && apt-get install -y ca-certificates openssl git curl golang python-is-python3 && \
I splitted this RUN to potentially save some time, that we hopefully at least sometimes can use a cached version of this step. Should not hurt anyway

2024-10-28 07:50 UTC, MP91 requested changes

2024-10-28 07:50 UTC, MP91 commented on .devcontainer/Dockerfile
>  RUN apt-get update && apt-get install -y ca-certificates openssl git curl golang python-is-python3 && \
I guess anything with apt update will never be cached, but I never tested it

2024-10-28 07:50 UTC, MP91 commented on .devcontainer/devcontainer.json
> +	"postStartCommand": "nohup bash -c 'hugo server -b http://localhost/velocitas -w &'"
seems to work, but now I have to open nohup.out to see the url of the hosted page. could you please check if it is possible to still show the logs otherwise please add the nohup.out to the gitignore

2024-10-28 07:50 UTC, MP91 commented on README.md
> +  `https://<your userid or organization>.github.io/velocitas-docs/`.
```suggestion
* Run the hugo server on localhost
* Verify that appearance is similar to the [currently deployed official version](https://eclipse.dev/velocitas/) and links are working as expected.
* Upload the new `main` to a fork that you control with GitHub Pages enabled
* Verify that you can run the `Publish Documentation` workflow and that the result is published to your pages. Use a GitHub Pages configuration where the `docs` branch is used and where the result will be available at `https://<your userid or organization>.github.io/velocitas-docs/`.
```

2024-10-28 07:50 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_client.md
> +In the `AppManifest.json` file you need to specify which interfaces your App wants to use or provide.
```suggestion
In the `AppManifest.json` file you need to specify which interfaces your App wants to use.
```

2024-10-28 07:50 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_client.md
> +but the SDK has been updated in the background so you can use it in the file containing `main()`.
```suggestion
When rebuilding the devcontainer with the configuration no new files will appear in your repository, but the SDK has been updated in the background so you can use it in the file containing `main()`.
```

2024-10-28 07:50 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_client.md
> +succeeds it tries to read current position.
```suggestion
In this example we modify the file `Launcher.cpp` that already exists in the [template](https://github.com/eclipse-velocitas/vehicle-app-cpp-template).
The logic of the example client is simple. It tries to set the target position for the seat and if it succeeds it tries to read current position.
```

2024-10-28 07:50 UTC, MP91 commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +2024-10-22 09:51:41, INFO  : Server sdv::edge::comfort::seats::v1::Seats listening on 127.0.0.1:5556
where is the 5556 port coming from? shouldn't it be 5555 as per env definition?

2024-10-28 13:54 UTC, erikbosch commented on .devcontainer/Dockerfile
>  RUN apt-get update && apt-get install -y ca-certificates openssl git curl golang python-is-python3 && \
Apparently it caches things at least sometimes - in general I think the caching is quite stupid, it does not analyze the content (in this case `apt`). I assume it is first when you rebuild the devcontainer "without cache" that you are guaranteed to get an updated `javascript-node` (if available) and new version sof the apt packages

https://pythonspeed.com/articles/docker-cache-insecure-images/

2024-10-28 15:33 UTC, erikbosch commented on .devcontainer/devcontainer.json
> +	"postStartCommand": "nohup bash -c 'hugo server -b http://localhost/velocitas -w &'"
It does not seem to possible to show output of the nohup, but we could add an extra printout giving some hints, will include that in an upcoming commit

2024-10-28 15:39 UTC, erikbosch commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +2024-10-22 09:51:41, INFO  : Server sdv::edge::comfort::seats::v1::Seats listening on 127.0.0.1:5556
Copy/paste error, port 5555 was not properly closed in one run, so I had to use another port, will address it.

2024-10-29 11:43 UTC, erikbosch commented on content/en/docs/tutorials/grpc_service_generation/create_server.md
> +In the `AppManifest.json` file you need to specify which interfaces your server will provide.
This is getting a bit philosophical. From a gRPC/Proto-pespective - what is actually the interface? Is it the service definition, or is each rpc/method in the service definition considered as an interface? Some quick googling did not give a clear answer :-)

To avoid this ambiguity we could rephrase to something like:

_In the `AppManifest.json` file you need to specify all gRPC services your application will use, either as a client or a server. For a server you need to specify `"provided": { }`. It is not needed and not supported to specify individual methods, as the generated code will include all methods defined in the gRPC service._

That way we avoid the ambiguous word _interface_, and instead state what I think we agree on - that you must list all gRPC services, but you do need (and cannot) to list gRPC methods/rpcs.

2024-10-29 12:18 UTC, MP91 approved these changes
LGTM

Only merge after the SDK PR is merged

2024-10-30 09:15 UTC, merged