Added addiional information and solved broken link
eclipse-velocitas/velocitas-docs pull request #22
Opened 2022-08-03 07:25 UTC by gkreyssing

## Describe your changes

Added additional information about Vehicle Service and Vehicle Model and solved broken link

2022-08-03 11:35 UTC, doosuu requested changes

2022-08-03 11:35 UTC, doosuu commented on content/en/docs/tutorials/tutorial_how_to_create_a_vehicle_model.md
> +  Learn how to create a Vehicle Model to get assess vehicle data or execute remote procedure calls.
`to get assess vehicle data or execute remote procedure calls. `
should be 
`to get access to vehicle data or execute remote procedure calls.`

2022-08-03 11:35 UTC, doosuu commented on content/en/docs/tutorials/tutorial_how_to_create_a_vehicle_model.md
> +A Vehicle Model should be defined in its own package. This makes it possible to distribute the Vehicle Model later as a standalone package and to use it in different _Vehicle App_ projects.
_Vehicle App_ is in italics here, should we apply this formatting throughout the entire document?

2022-08-03 19:50 UTC, gkreyssing commented on content/en/docs/tutorials/tutorial_how_to_create_a_vehicle_model.md
> +A Vehicle Model should be defined in its own package. This makes it possible to distribute the Vehicle Model later as a standalone package and to use it in different _Vehicle App_ projects.
Changed to _Vehicle App_ in the whole document

2022-08-08 05:26 UTC, doosuu approved these changes

2022-08-08 07:08 UTC, merged