Documentation update according to changes in Vehicle Template
eclipse-velocitas/velocitas-docs pull request #26
Opened 2022-08-12 09:40 UTC by mml5bg

## Describe your changes
Documentation update according to the changes implemented in https://github.com/eclipse-velocitas/vehicle-app-python-template/pull/15
## Issue ticket number and link

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

2022-08-29 15:38 UTC, BjoernAtBosch requested changes

2022-08-29 15:38 UTC, BjoernAtBosch commented on content/en/docs/tutorials/vehicle-app-runtime/run_runtime_services_locally.md
> +* (Optional) Vehicle Services (```Local - VehicleServices```): runs _Vehicle Services_, an example `Seat Service` as a container
```suggestion
* (Optional) Vehicle Services (```Local - VehicleServices```): runs the _Vehicle Services_ (e.g. the `Seat Service`) configured in the `AppManifest.json` as each a separate container
```

2022-08-29 15:38 UTC, BjoernAtBosch commented on content/en/docs/tutorials/vehicle-app-runtime/run_runtime_services_locally.md
>  * Dapr (```Local - Ensure Dapr```): installs Dapr CLI and initializes Dapr if required
I've a discussion point for a bigger round (if my understanding is correct):

Regarding "Local" vs. "K3D": Maybe I've a limited understanding, but is "local" a good "opposite" to "K3D"? I mean is the run in k3d not also done on the local machine?

Wouldn't it then better to talk about "unmanged" and "K3D"?

2022-08-30 09:40 UTC, mml5bg commented on content/en/docs/tutorials/vehicle-app-runtime/run_runtime_services_locally.md
>  * Dapr (```Local - Ensure Dapr```): installs Dapr CLI and initializes Dapr if required
From my point of view it is correct, but let's discuss about it in bigger round, this is not in scope of this PR

2022-08-30 10:09 UTC, BjoernAtBosch commented on content/en/docs/tutorials/vehicle-app-runtime/run_runtime_services_locally.md
>  * Dapr (```Local - Ensure Dapr```): installs Dapr CLI and initializes Dapr if required
Yes, Dennis was also asking about that. I asked him to create a task for that.

2022-08-30 10:10 UTC, BjoernAtBosch approved these changes

2022-08-30 11:04 UTC, merged