Add initial version of C++ documentation
eclipse-velocitas/velocitas-docs pull request #27
Opened 2022-08-14 21:16 UTC by doosuu

## Describe your changes

Extended documentation with relevant parts for the C++ SDK.

## Issue ticket number and link
https://softwaredefinedvehicle.visualstudio.com/SoftwareDefinedVehicle/_workitems/edit/10702

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [x] Do we need to implement analytics?
- [x] Will this be part of a product update? If yes, please write one phrase about this update.

2022-08-16 08:37 UTC, MP91 requested changes

2022-08-16 08:37 UTC, MP91 commented on content/en/docs/tutorials/tutorial_how_to_create_a_vehicle_model/_index.md
> +        | cpp    | c++ sources, headers and a CMakeLists.txt ready to be used as a CMake project |
the output is not very readable, please add some space between the columns

2022-08-16 08:37 UTC, MP91 commented on content/en/docs/tutorials/tutorial_how_to_create_a_vehicle_model/_index.md
> +  5. Now the newly generated `sdv_model` can be used for distribution. (See [Distributing your Python Vehicle Model](#distributing-your-python-vehicle-model))
please adjust the link

2022-08-16 08:37 UTC, MP91 commented on content/en/docs/tutorials/tutorial_how_to_deploy_a_vehicle_app_with_helm.md
> +- Completed the tutorial [How to create a vehicle app]({{< ref "/docs/tutorials/vehicle-app-development" >}})
please use plain md if possible

2022-08-16 08:37 UTC, MP91 commented on content/en/docs/tutorials/vehicle-app-development/tutorial_how_to_create_a_vehicle_app_python.md
> +> We recommend that you make yourself familiar with the [Vehicle App SDK]({{< ref "vehicle_app_sdk" >}} "SDK Overview") first, before going through this tutorial.
please use plain md

2022-08-16 08:54 UTC, dennismeister93 commented on content/en/docs/concepts/vehicle_app_sdk/_index.md
> +The convencience layer of C++ is abit more extensive than in Python. The complexity of gRPC's async API is hidden behind individual `AsyncGrpcFacade` implementations which need to be implemented manu
```suggestion
The convencience layer of C++ is abit more extensive than in Python. The complexity of gRPC's async API is hidden behind individual `AsyncGrpcFacade` implementations which need to be implemented manually. Have a look at the `SeatAdjusterApp` example's `SeatService` and its `SeatServiceAsyncGrpcFacade`.
```

2022-08-16 09:03 UTC, dennismeister93 commented on content/en/docs/concepts/vehicle_app_sdk/_index.md
>  Subscriptions to MQTT topics can be easily established with the `subscribe_topic()` annotation. The annotation needs to be applied to a method of the `Vehicle App` class.
i think the annotation implementation is only valid for python

2022-08-16 09:10 UTC, dennismeister93 commented on content/en/docs/concepts/vehicle_app_sdk/_index.md
> +        : VehicleApp(IVehicleAdataBrokerClient::createInstance("vehicledatabroker")),
Is the A a typo in "IVehicleAdataBrokerClient" ?

2022-08-16 09:17 UTC, dennismeister93 commented on content/en/docs/tutorials/quickstart.md
>  ## Starting Development Environement
```suggestion
## Starting Development Environment
```

2022-08-16 09:23 UTC, dennismeister93 commented on content/en/docs/tutorials/tutorial_how_to_create_a_vehicle_model/_index.md
> +  Learn how to create a Vehicle Model to get to access vehicle data or execute remote procedure calls.
```suggestion
  Learn how to create a Vehicle Model to get access to vehicle data or execute remote procedure calls.
```

2022-08-16 09:31 UTC, dennismeister93 commented on content/en/docs/tutorials/tutorial_how_to_create_a_vehicle_model/distribution_python.md
> +If you want to distribute your Python _Vehicle Model_ to a single _Vehicle App_, you can do so by copying the entire folder `my_vehicle_model` under the `src` folder of your _Vehicle App_ repository
```suggestion
If you want to distribute your Python _Vehicle Model_ to a single _Vehicle App_, you can do so by copying the entire folder `my_vehicle_model` under the `src` folder of your _Vehicle App_ repository and treat it as a sub-package of the _Vehicle App_.
```

2022-08-16 09:58 UTC, dennismeister93 commented on content/en/docs/tutorials/vehicle-app-development/tutorial_how_to_create_a_vehicle_app_cpp.md
> +The following information describes how to develop and test the sample Vehicle App that is included in the [template repository](https://github.com/eclipse-velocitas/vehicle-app-python-template). You
Link refers to python template

2022-08-16 09:59 UTC, dennismeister93 commented on content/en/docs/tutorials/vehicle-app-development/tutorial_how_to_create_a_vehicle_app_cpp.md
> +- [How to create a Vehicle Model](/docs/python-sdk/tutorial_how_to_create_a_vehicle_model.md)
This link ends up in 404

2022-08-16 10:08 UTC, dennismeister93 commented on content/en/docs/tutorials/vehicle-app-development/tutorial_how_to_create_a_vehicle_app_cpp.md
> +The first thing you need to do to get access to the Vehicle Model. In the section about [distributing a model]({{< ref "tutorial_how_to_create_a_vehicle_model.md#distributing-your-python-vehicle-mode
```suggestion
The first thing you need to do to get access to the Vehicle Model. In the section about [distributing a model]({{< ref "tutorial_how_to_create_a_vehicle_model.md#distributing-your-vehicle-model" >}}), you got to know the different methods.
```

2022-08-16 10:17 UTC, dennismeister93 commented on content/en/docs/tutorials/vehicle-app-development/tutorial_how_to_create_a_vehicle_app_cpp.md
> +We specify which python-script to run using the `program` key. With the `preLaunchTask` and `postDebugTask` keys, you can also specify tasks to run before or after debugging. In this example, DAPR is
it's not a python script here

2022-08-17 06:51 UTC, MP91 approved these changes

2022-08-18 05:46 UTC, merged