Doc/10868 extract seatadjuster app to sdk
eclipse-velocitas/velocitas-docs pull request #32
Opened 2022-08-31 08:36 UTC by dennismeister93

## Describe your changes

Update documentation to adaptions in the template repository describing how to run the new skeleton app and also how to import example Vehicle Apps provided in the SDK package

## Issue ticket number and link

[AB#_[10868]_](https://softwaredefinedvehicle.visualstudio.com/SoftwareDefinedVehicle/_workitems/edit/10868)

## Checklist before requesting a review
- [x] I have performed a self-review of my code

2022-09-05 16:19 UTC, emsameen approved these changes

2022-09-05 16:19 UTC, emsameen commented on content/en/docs/tutorials/tutorial_how_to_create_a_vehicle_model/manual_creation_python.md
> +        Successfully installed sdv-x.x.x
OPTIONAL: x.y.z or a.b.c, ...

2022-09-05 16:19 UTC, emsameen commented on content/en/docs/tutorials/vehicle-app-development/tutorial_how_to_create_a_vehicle_app_cpp.md
> +At first, you have to create the main c++ file which we will call `App.cpp` in `/app/src`. All the relevant code for new _Vehicle App_ goes there. Afterwards, there are several steps you need to cons
Are you sure of the C++ ? 
- This needs to aligned with the c++ team

2022-09-05 16:19 UTC, emsameen commented on content/en/docs/tutorials/vehicle-app-development/tutorial_how_to_create_a_vehicle_app_python.md
> +For this tutorial, you will recreate the vehicle app that is included with the [SDK repository](https://github.com/eclipse-velocitas/vehicle-app-python-sdk/tree/main/examples/seat-adjuster):
I think it make sense to include in the tutorials the sample app on the template instead of creating the seat adjuster app from the SDK. 
- The sample app is much simpler and more generic for the tutorials from my point of view.

2022-09-05 16:20 UTC, emsameen requested changes
We need to discuss the necessary changes

2022-09-05 16:59 UTC, dennismeister93 commented on content/en/docs/tutorials/vehicle-app-development/tutorial_how_to_create_a_vehicle_app_cpp.md
> +At first, you have to create the main c++ file which we will call `App.cpp` in `/app/src`. All the relevant code for new _Vehicle App_ goes there. Afterwards, there are several steps you need to cons
I only added the "/" before app :) i didn't touch the c++ content

2022-09-05 17:02 UTC, dennismeister93 commented on content/en/docs/tutorials/vehicle-app-development/tutorial_how_to_create_a_vehicle_app_python.md
> +For this tutorial, you will recreate the vehicle app that is included with the [SDK repository](https://github.com/eclipse-velocitas/vehicle-app-python-sdk/tree/main/examples/seat-adjuster):
Agree! Will adapt to the sample app :) just thought of having this makes sense because its an actual example which uses a service (seat service) what do you think of keeping the part with the seat adjuster on an extra tab but primarily also adding the sample app?

2022-09-06 12:01 UTC, dennismeister93 commented on content/en/docs/tutorials/vehicle-app-development/tutorial_how_to_create_a_vehicle_app_python.md
> +For this tutorial, you will recreate the vehicle app that is included with the [SDK repository](https://github.com/eclipse-velocitas/vehicle-app-python-sdk/tree/main/examples/seat-adjuster):
As discussed, improved the seat adjuster example documentation

2022-09-06 16:05 UTC, emsameen approved these changes
LGTM

2022-09-06 16:05 UTC, merged