fix: update workflow documentation
eclipse-velocitas/velocitas-docs pull request #33
Opened 2022-09-06 14:47 UTC by emsameen

## Describe your changes

- chnage the Continuous Integration behaviour where the imgaes are pushed to the container registry only on the release workflow not on the continuous integration anymore.
 

## Issue ticket number and link

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

2022-09-07 11:25 UTC, BjoernAtBosch requested changes

2022-09-07 11:25 UTC, BjoernAtBosch commented on content/en/docs/about/deployment_model/vehicle_app_releases/_index.md
> +  On every new push to the `main` branch or every update to Pull Request, a GitHub workflow is automatically executed to build your application as a container (optionally for different platforms), ru
```suggestion
  On every new push to the `main` branch or every update to a pull request, a GitHub workflow is automatically executed to build your application as a container (optionally for different platforms), runs automated tests and code quality checks, and stores all results as GitHub artifacts for future reference with a default retention period of 90 days.
```

2022-09-07 11:25 UTC, BjoernAtBosch commented on content/en/docs/about/deployment_model/vehicle_app_releases/_index.md
> +  On every new push to the `main` branch or every update to Pull Request, a GitHub workflow is automatically executed to build your application as a container (optionally for different platforms), ru
What about the generated container: Is that stored as a build artefact or is it stored in ghcr?
In latter case: Is retention period the same?

2022-09-07 11:25 UTC, BjoernAtBosch commented on content/en/docs/about/deployment_model/vehicle_app_releases/_index.md
> +  The release workflow bundles all relevant artifacts into one tagged set of files and makes it possible to push this information to the preferred container registry of your choice (e.g. to be used f
```suggestion
  The release workflow bundles all relevant artifacts into one tagged set of files and makes it possible to push this information to the preferred container registry of your choice (e.g. to be used for an over-the-air update container registry) or use the information for quality assurance and documentation.
```

2022-09-07 11:25 UTC, BjoernAtBosch commented on content/en/docs/about/deployment_model/vehicle_app_releases/_index.md
> +The `Continuous Integration (CI) workflow` is triggered on every commit to the main branch or when creating/updating a Pull Request and contains a set of different actions that cover:
```suggestion
The `Continuous Integration (CI) workflow` is triggered on every commit to the main branch or when creating/updating a pull request and contains a set of different actions that cover:
```

2022-09-07 11:25 UTC, BjoernAtBosch commented on content/en/docs/about/deployment_model/vehicle_app_releases/_index.md
> +- **Building a container for the app** - actions create a containerized version of the Vehicle App, the actions also support creating an image for multiple platforms and CPU architectures.
Is really multiple actions mentioned here or just a single action?
(Asking because of using the plural here)

2022-09-07 11:25 UTC, BjoernAtBosch commented on content/en/docs/about/deployment_model/vehicle_app_releases/_index.md
>  - **Storing scan & test results as GitHub action artifacts** - actions store results from the previously mentioned actions for further reference or download as Github Action Artifacts.
Is using plural ("actions") correct?

2022-09-07 11:25 UTC, BjoernAtBosch commented on content/en/docs/about/deployment_model/vehicle_app_releases/_index.md
> +- **Pull & label container image** - actions pull the Vehicle App container image based on the current commit hash from the GitHub Artifacts and label it with the specified tag version. If the image
```suggestion
- **Pull & label container image** - actions pull the Vehicle App container image based on the current commit hash from the GitHub artifacts and label it with the specified tag version. If the image cannot be found, the workflow will fail.
```

2022-09-07 18:30 UTC, emsameen commented on content/en/docs/about/deployment_model/vehicle_app_releases/_index.md
> +- **Building a container for the app** - actions create a containerized version of the Vehicle App, the actions also support creating an image for multiple platforms and CPU architectures.
They are set of sequential actions to build, scan and publish the container images.

2022-09-07 18:33 UTC, emsameen commented on content/en/docs/about/deployment_model/vehicle_app_releases/_index.md
>  - **Storing scan & test results as GitHub action artifacts** - actions store results from the previously mentioned actions for further reference or download as Github Action Artifacts.
Yes, as above.

2022-09-07 18:37 UTC, emsameen commented on content/en/docs/about/deployment_model/vehicle_app_releases/_index.md
> +  On every new push to the `main` branch or every update to Pull Request, a GitHub workflow is automatically executed to build your application as a container (optionally for different platforms), ru
The release workflow pushes the images to the container registry and just use the created artifacts from the CI workflow.
Images on the container registry have no retention period. They have to be removed manually or even to define a cleaning up strategy on the organization level.

2022-09-08 10:36 UTC, BjoernAtBosch commented on content/en/docs/about/deployment_model/vehicle_app_releases/_index.md
> +- **Building a container for the app** - actions create a containerized version of the Vehicle App, the actions also support creating an image for multiple platforms and CPU architectures.
Hmh , I still find this a bit confusing because:
1. We are talking here about a GitHub workflows and the term "action(s)" may trigger thinking of a GitHub action, what this is not. It's jobs and steps. So, maybe another term would be less misleading, e.g. "activity", "task", or "procedure".
2. More important: In the sentence above this enumeration list, it's stated that the CI workflow "[...] contains a set of different **actions** that cover:" and then in the list itself, where I would expect that each single **action** is enumerated, we still speak of "actions" (in plural).

2022-09-08 16:43 UTC, emsameen commented on content/en/docs/about/deployment_model/vehicle_app_releases/_index.md
> +- **Building a container for the app** - actions create a containerized version of the Vehicle App, the actions also support creating an image for multiple platforms and CPU architectures.
I think the sentences was writing already before and I didn't change them here, I just updated some but I didn't invent that. 
From the other side, it is really multiple (actions/tasks/activities, whatever you call them) also called within the single stage. 
Please look to the [Build Image] (https://github.com/eclipse-velocitas/vehicle-app-python-template/blob/main/.github/workflows/build-docker-image.yml) sub-workflow which also internally has multiple activities. This workflow also called from the CI workflow.
I don't really see any objection with that but please feel free to have any suggestions and I will take them :)
- Just let me what do I need to change :) 
Thanks!

2022-09-08 16:47 UTC, emsameen commented on content/en/docs/about/deployment_model/vehicle_app_releases/_index.md
>  - **Scanning for vulnerabilities** - actions scan your code and container for vulnerabilities and in case of findings the workflow will be marked as "failed".
No, I think the scanning here is not the same as the code scanning in the CodeQL.
- Here the container image is scanned from vulnerabilities via some Github action after image creation. --> Again, I just updated the behaviour and not the context :)

2022-09-13 08:57 UTC, gkreyssing requested changes

2022-09-13 09:29 UTC, BjoernAtBosch commented on content/en/docs/about/deployment_model/vehicle_app_releases/_index.md
> +The `Continuous Integration (CI) workflow` is triggered on every commit to the main branch or when creating/updating a pull request and contains a set of different actions that cover:
@emsameen: How do you think of this:
```suggestion
The `Continuous Integration (CI) workflow` is triggered on every commit to the main branch or when creating/updating a pull request and contains a set of actions to achieve the following objectives:
```

2022-09-13 09:30 UTC, BjoernAtBosch commented on content/en/docs/about/deployment_model/vehicle_app_releases/_index.md
>  The set of actions included in the `Release workflow` cover:
```suggestion
The set of actions included in the `Release workflow` cover the objectives:
```

2022-09-13 12:13 UTC, emsameen commented on content/en/docs/about/deployment_model/vehicle_app_releases/_index.md
Done

2022-09-13 14:26 UTC, BjoernAtBosch approved these changes

2022-09-14 09:24 UTC, gkreyssing requested changes

2022-09-14 09:24 UTC, gkreyssing commented on content/en/docs/about/deployment_model/vehicle_app_releases/_index.md
> +  The release workflow bundles all relevant images and artifacts into one tagged set of files and makes it possible to be pushed to the GitHub Container Registry as well as for the information to be
```suggestion
  The release workflow bundles all relevant images and artifacts into one tagged set of files and push it to the GitHub Container Registry. In addition, it makes the information ready to be used for quality assurance and documentation accordingly. The image in GitHub Container Registry can be used in your preferred  Over-The-Air (OTA) update system of your choice.
```

2022-09-14 09:42 UTC, merged