[Fix] Correct config.json content
eclipse-velocitas/velocitas-docs pull request #38
Opened 2022-09-29 07:40 UTC by kse3hi

## Describe your changes

## Issue ticket number and link

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

2022-10-04 09:18 UTC, MP91 requested changes

2022-10-04 09:18 UTC, MP91 commented on content/en/docs/tutorials/quickstart/behind_proxy.md
> +              "allProxy": "http://host.docker.internal:3128",
where is this used?

2022-10-04 09:18 UTC, MP91 commented on content/en/docs/tutorials/quickstart/behind_proxy.md
> +              "noProxy": "localhost,127.*,0.0.0.0,10.*,192.*,172.*,cattle-system.svc,.svc,.cluster.local"
why should I add kubernetes stuff to my local config if I don't have kubernetes on my machine?

2022-11-29 09:28 UTC, kse3hi commented on content/en/docs/tutorials/quickstart/behind_proxy.md
> +              "allProxy": "http://host.docker.internal:3128",
For now nowhere, but I would like to keep it for the future.

2022-11-29 09:30 UTC, kse3hi commented on content/en/docs/tutorials/quickstart/behind_proxy.md
> +              "noProxy": "localhost,127.*,0.0.0.0,10.*,192.*,172.*,cattle-system.svc,.svc,.cluster.local"
In the end we override it on our ./configure_proxy script. Ideal variant will be rid off of the configuration script at all.
I'd prefer to have it here as additional level of protection.

2022-11-30 06:40 UTC, MP91 requested changes

2022-11-30 06:40 UTC, MP91 commented on content/en/docs/tutorials/quickstart/behind_proxy.md
> +              "allProxy": "http://host.docker.internal:3128",
If we don't need it -> please remove it. It is just confusing. We want to have a minimal setup

2022-11-30 06:40 UTC, MP91 commented on content/en/docs/tutorials/quickstart/behind_proxy.md
> +              "noProxy": "localhost,127.*,0.0.0.0,10.*,192.*,172.*,cattle-system.svc,.svc,.cluster.local"
since we are overriding it and can't get rid of the script since we are also configuring other tools -> please revert this. We want to have a minimal working setup. This is just confusing.

2022-12-12 12:50 UTC, kse3hi commented
Not relevant due to PR-64

2022-12-12 12:50 UTC, closed without merging