Added feature overview
eclipse-velocitas/velocitas-docs pull request #60
Opened 2022-11-04 21:10 UTC by gkreyssing

## Describe your changes

## Issue ticket number and link

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

2022-11-08 12:16 UTC, doosuu requested changes

2022-11-08 12:16 UTC, doosuu commented on content/en/docs/about/_index.md
> +|Vehilce App Template | + | + |
```suggestion
|Vehicle App Template | + | + |

```

2022-11-08 12:16 UTC, doosuu commented on content/en/docs/about/_index.md
> +|Vehilce App SDK | + | + |
```suggestion
|Vehicle App SDK | + | + |

```

2022-11-08 12:16 UTC, doosuu commented on content/en/docs/about/_index.md
> +|Vehicle Model generator| + | + |
```suggestion
|Vehicle Model Generator| + | + |

```

2022-11-08 12:16 UTC, doosuu commented on content/en/docs/about/_index.md
> +|DevConatiner for esay IDE setup | + | + |
```suggestion
|DevContainer for easy IDE setup | + | + |

```

2023-01-26 17:15 UTC, emsameen requested changes
I think the table is broken ?

2023-02-14 09:32 UTC, BjoernAtBosch approved these changes
LGTM

2023-02-14 09:35 UTC, doosuu approved these changes
LGTM

2023-02-14 09:38 UTC, merged