Add Lifecycle management
eclipse-velocitas/velocitas-docs pull request #76
Opened 2023-02-16 15:45 UTC by dennismeister93

## Describe your changes

Add lifecycle management concept to documentation

## Issue ticket number and link

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [x] Will this be part of a product update? If yes, please write one phrase about this update.

2023-02-17 15:22 UTC, doosuu requested changes
Please add a diagram showing the flow through the lifecycle management:

`[devContainer]` `-onCreateCommand->` `velocitas init`-> `velocitas sync` -> `velocitas upgrade --dry-run` -> `velocitas upgrade` -> `velocitas sync`...

2023-02-17 15:22 UTC, doosuu commented on content/en/docs/concepts/lifecycle_management/cli.md
> +It is written in TypeScript and based on the open CLI framework [oclif](https://oclif.io/).
```suggestion
```
Too much information for an overarching documentation. If we ever change the language or framework, we will have to adapt this line.

2023-02-17 15:22 UTC, doosuu commented on content/en/docs/concepts/lifecycle_management/cli.md
> +{{<table "table table-bordered">}}
Remove command explainations and point to cli/README.md#commands

2023-02-17 15:22 UTC, doosuu commented on content/en/docs/concepts/lifecycle_management/cli.md
> +* Lifecycle Management: [Troubleshoot](/docs/concepts/lifecycle_management/troubleshooting/)
```suggestion
* Lifecycle Management: [Troubleshooting](/docs/concepts/lifecycle_management/troubleshooting/)
```

2023-02-17 15:22 UTC, doosuu commented on content/en/docs/concepts/lifecycle_management/packages/development.md
> +* [devenv-devcontainer-setup](https://github.com/eclipse-velocitas/devenv-devcontainer-setup/blob/main/manifest.json)
```suggestion
* [devenv-devcontainer-setup manifest](https://github.com/eclipse-velocitas/devenv-devcontainer-setup/blob/main/manifest.json)
```

2023-02-17 16:18 UTC, dennismeister93 commented on content/en/docs/about/_index.md
> +{{<table "table table-bordered">}}
I think that is probably not possible to have a generally styled table, since hugo is a static site generator which uses markdownify with shortcodes to "change out" <table> elements to <table class=\"%s\">  with classes to style them

2023-02-20 15:38 UTC, kse3hi requested changes

2023-02-20 15:38 UTC, kse3hi commented on content/en/docs/concepts/lifecycle_management/cli.md
> +title: "CLI"
All references is named as Velocitas CLI, probably we should to keep it as well for consistency?

2023-02-20 15:38 UTC, kse3hi commented on content/en/docs/concepts/lifecycle_management/cli.md
> +vscode ➜ /workspaces/eclipse-vehicle-app-python-template (main) $ ./velocitas-cli/bin/dev exec runtime-local run-vehicledatabroker
In CLI Readme command for exec is different: 
`USAGE
  $ velocitas exec [COMPONENT] [ID] [-v] [--args <value>]`
Should we align it?

2023-02-20 16:43 UTC, doosuu commented on content/en/docs/about/repository-overview/_index.md
> +| [vehicle-app-cpp-sdk](https://github.com/eclipse-velocitas/vehicle-app-cpp-sdk)                   | Provides basic functionality to write an SDK to allow access to vehicle data points and method. T
I concur, `an SDK` is way easier to read and speak. See https://www.redhat.com/en/topics/cloud-native-apps/what-is-SDK

2023-02-21 09:10 UTC, kse3hi approved these changes
LGTM

2023-02-21 11:14 UTC, MP91 requested changes
Just some small findings

2023-02-21 11:14 UTC, MP91 commented on content/en/docs/concepts/lifecycle_management/packages/development.md
> +Create a repo at `https://my-organization/repos/my-velocitas-package.git` (e.g., `https://github.com/my-organisation/my-velocitas-package`).
this is not a good example IMO.

2023-02-21 11:14 UTC, MP91 commented on content/en/docs/concepts/lifecycle_management/velocitas-cli.md
> +### velocitas sync
For me it is still not clear where the difference between init and sync is. Could you clarify this?

2023-02-21 11:14 UTC, MP91 commented on content/en/docs/concepts/lifecycle_management/troubleshooting.md
> +
please mention the devcontainer

2023-02-21 12:16 UTC, MP91 approved these changes
LGTM

2023-02-21 16:44 UTC, dennismeister93 commented on content/en/docs/concepts/lifecycle_management/_index.md
> +are (or will be) provided as versioned [packages](/docs/concepts/lifecycle_management/packages/) which can be updated individually, if required.
i would not see them as "cli" packages only, i would say they are packages belonging to a vehicle app/velocitas/vadf

2023-02-21 16:51 UTC, BjoernAtBosch commented on content/en/docs/concepts/lifecycle_management/_index.md
> +are (or will be) provided as versioned [packages](/docs/concepts/lifecycle_management/packages/) which can be updated individually, if required.
Hmh, yes. Also, CLI packages could of course also be interpreted as being part of the CLI and not just managed by CLI.

It's just about, that I find just "packages" too common. But also have no "powerful" better idea. So, let's keep it for time being ...

2023-02-21 16:52 UTC, BjoernAtBosch approved these changes
LGTM

2023-02-21 16:57 UTC, merged