Correct requestId being a number
eclipse-velocitas/velocitas-docs pull request #81
Opened 2023-03-07 14:28 UTC by BjoernAtBosch

## Describe your changes

## Issue ticket number and link

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

2023-03-08 05:44 UTC, doosuu commented on content/en/docs/tutorials/automated_model_lifecycle.md
> +A _Vehicle Model_ makes it possible to easily access vehicle data at the KUKSA Data Broker. It is generated from the underlying semantic model specification for a concrete programming language as a g
```suggestion
A _Vehicle Model_ makes it possible to easily access vehicle data at the [KUKSA Data Broker](https://github.com/eclipse/kuksa.val/tree/master/kuksa_databroker). It is generated from the underlying semantic model specification for a concrete programming language as a graph-based, strongly-typed, intellisense-enabled library.
```

2023-03-08 05:47 UTC, doosuu commented on content/en/docs/tutorials/automated_model_lifecycle.md
> +{{% alert title="Info" %}} This article describes our new model lifecycle approach released on Friday, 2023-03-03. With that, the model is now automatically generated with the instantiation of the de
```suggestion
{{% alert title="Info" %}} This article describes our new model lifecycle approach released on Friday, 2023-03-03. With that, the model is now automatically generated with the instantiation of the devContainer. It is generated from the vehicle model source file referenced in the AppManifest.
```

2023-03-08 05:49 UTC, doosuu commented on content/en/docs/tutorials/automated_model_lifecycle.md
> +A _Vehicle Model_ makes it possible to easily access vehicle data at the KUKSA Data Broker. It is generated from the underlying semantic model specification for a concrete programming language as a g
Missing that the model is based on VSS.

2023-03-08 05:52 UTC, doosuu commented on content/en/docs/tutorials/automated_model_lifecycle.md
> +- [Visual Studio Code](https://code.visualstudio.com/) with the [Python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python) installed. For information on how to install e
Why is the Python extension needed?

2023-03-08 05:58 UTC, doosuu commented on content/en/docs/tutorials/automated_model_lifecycle.md
> +The model specification defines the vehicle API to be used by your project. It is referenced in the `AppManifest.json` via an URI like this:
```suggestion
The model specification defines the vehicle API to be used by your project. It is referenced in the `AppManifest.json` via a URI like this: 
```

Should be _a_ for better readability since you read the U as `you`

2023-03-08 06:02 UTC, doosuu commented on content/en/docs/tutorials/automated_model_lifecycle.md
> +* automatically during the instantiation of the dev-container through our Velocitas lifecycle management,
Add a link to the lifecycle management tutorial. Lifecycle documentation is missing an extension for post init hooks.

2023-03-08 06:21 UTC, doosuu commented on content/en/docs/tutorials/automated_model_lifecycle.md
> +![](./model_lifecycle.svg)
In the SVG, please add white outlines to the arrows and text that cross the boundaries - they are not visible / readable in a dark theme

2023-03-08 06:25 UTC, doosuu commented on content/en/docs/tutorials/tutorial_how_to_create_a_vehicle_model/_index.md
> +{{% alert title="Info" %}} On Friday, 2023-03-03 we released our [new model lifecycle approach](/docs/tutorials/automated_model_lifecycle.md). With that, the model is now automatically generated with
```suggestion
{{% alert title="Info" %}} On Friday, 2023-03-03 we released our [new model lifecycle approach](/docs/tutorials/automated_model_lifecycle.md). With that, the model is now automatically generated with the instantiation of the devContainer. The model is generated from the vehicle API referenced in the AppManifest. For the time being, the integration of services is not supported any more.
```

2023-03-08 06:27 UTC, doosuu requested changes
Can we split the correct requestId PR from the model lifecycle PR?

2023-03-08 07:43 UTC, dennismeister93 commented on content/en/docs/tutorials/tutorial_how_to_create_a_vehicle_model/_index.md
> +title: "Vehicle Model Creation (old)"
maybe flag this as "deprecated" ?

2023-03-08 07:44 UTC, dennismeister93 commented on content/en/docs/tutorials/automated_model_lifecycle.md
> +The "old" approach, using pre-generated model repositories, is still available and [described here](/docs/tutorials/tutorial_how_to_create_a_vehicle_model/).
also maybe "deprecated" instead of "old" an point out that we recommend using the automated approach

2023-03-08 14:55 UTC, BjoernAtBosch commented on content/en/docs/tutorials/automated_model_lifecycle.md
> +* automatically during the instantiation of the dev-container through our Velocitas lifecycle management,
Lifecycle docu will be added by Dennis

2023-03-08 14:55 UTC, BjoernAtBosch commented on content/en/docs/tutorials/automated_model_lifecycle.md
> +![](./model_lifecycle.svg)
As discussed, no dark theme avail on the webpage

2023-03-09 16:09 UTC, dennismeister93 approved these changes
lgtm

2023-03-09 21:14 UTC, doosuu requested changes

2023-03-09 21:14 UTC, doosuu commented on content/en/docs/tutorials/vehicle-app-development/tutorial_how_to_create_a_vehicle_app_python.md
> +The first thing you need to do to get access to the Vehicle Model. If you derived your project repository from our template, we already provide a generated model installed as a Python package named `
```suggestion
The first thing you need to do is to get access to the Vehicle Model. If you derived your project repository from our template, we already provide a generated model installed as a Python package named `vehicle`. Hence in most cases no additional setup is necessary. How to tailor the model to your needs or how you could get access to vehicle services is described in the tutorial linked above.
```

2023-03-09 21:14 UTC, doosuu commented on content/en/docs/tutorials/vehicle_model_creation/automated_model_lifecycle/_index.md
> +The model is generated using our [Velocitas vehicle-model-generator](https://github.com/eclipse-velocitas/vehicle-model-generator). By default version 0.3.0 is used.
```suggestion
The model is generated using our [Velocitas vehicle-model-generator](https://github.com/eclipse-velocitas/vehicle-model-generator).
```

If we explicitly mention a default here, we will always have to adapt our documentation once we upgrade the default in the package.

2023-03-09 21:14 UTC, doosuu commented on content/en/docs/tutorials/vehicle_model_creation/automated_model_lifecycle/_index.md
> +In Python template based projects the generated model is finally installed in the site-packages folder, whereat in C++ projects it is made available as a cmake include folder.
```suggestion
In Python template based projects the generated model is finally installed in the site-packages folder, while in C++ projects it is made available as a CMake include folder.
```

2023-03-10 10:30 UTC, doosuu approved these changes
lgtm

2023-03-10 10:40 UTC, merged