Add custom vspec handling from digital auto
eclipse-velocitas/velocitas-docs pull request #84
Opened 2023-03-16 12:46 UTC by dennismeister93

## Describe your changes
Add custom vspec handling from digital auto
## Issue ticket number and link
[#12952](https://softwaredefinedvehicle.visualstudio.com/SoftwareDefinedVehicle/_workitems/edit/12952)
## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

2023-03-17 05:57 UTC, MP91 requested changes

2023-03-17 05:57 UTC, MP91 commented on content/en/docs/tutorials/prototyping/_index.md
> +If the ideation of your vehicle app prototype comes with any new Vehicle API which is not part of the standard [VSS](https://covesa.github.io/vehicle_signal_specification/introduction/) you also have
you need an account and must be contributor. please add this condition

2023-03-17 05:57 UTC, MP91 commented on content/en/docs/tutorials/prototyping/_index.md
> +If you press this button you will be forwarded to [GitHub](https://github.com/) to login with your GitHub Account and authorize [velocitas-project-generator](https://github.com/eclipse-velocitas/velo
The organisation can not yet be specified or?

2023-03-17 05:57 UTC, MP91 commented on content/en/docs/tutorials/prototyping/_index.md
> +- if your prototype includes any exceptional API you added beforehand our [automated vehicle model lifecycle](/docs/tutorials/vehicle_model_creation/automated_model_lifecycle) takes care of handling
please add the _/gen/ folder here

2023-03-17 05:57 UTC, MP91 commented on content/en/docs/tutorials/prototyping/run-section.png
all images are now larger (mostly higher). is this wanted?

2023-03-17 06:01 UTC, doosuu requested changes

2023-03-17 06:01 UTC, doosuu commented on content/en/docs/tutorials/prototyping/code-section.png
Add visual hints to the element of the website you want to want to emphasize.

2023-03-17 06:01 UTC, doosuu commented on content/en/docs/tutorials/prototyping/cvi-catalogue.png
Add visual hints to the element of the website you want to want to emphasize.

2023-03-17 06:01 UTC, doosuu commented on content/en/docs/tutorials/prototyping/generate.png
Add visual hints to the element of the website you want to want to emphasize.

2023-03-17 06:01 UTC, doosuu commented on content/en/docs/tutorials/prototyping/run-section.png
Add visual hints to the element of the website you want to want to emphasize.

2023-03-17 06:01 UTC, doosuu commented on content/en/docs/tutorials/prototyping/wishlist.png
Add visual hints to the element of the website you want to want to emphasize.

2023-03-17 12:07 UTC, MP91 requested changes

2023-03-17 12:07 UTC, MP91 commented on content/en/docs/tutorials/prototyping/_index.md
> +|_/.devcontainer/_| required scripts to install every prerequisite in Microsoft Visual Studio Code |
```suggestion
|_/.devcontainer/_| Required scripts and settings to setup the devcontainer in Microsoft Visual Studio Code |
```

2023-03-17 12:07 UTC, MP91 commented on content/en/docs/tutorials/prototyping/_index.md
> +|_/app/requirements.txt_| with definition of dependencies |
```suggestion
|_/app/AppManifest.json_| Settings file defining required services |
|_/app/requirements.txt_| Requirements file defining all python dependencies |
```

2023-03-17 12:07 UTC, MP91 commented on content/en/docs/tutorials/prototyping/_index.md
> +|_/.github/workflows/_| with all required CI/CD pipelines to build, test and deploy the vehicle application as container image to the GitHub container registry|
```suggestion
|_/.github/workflows/_| All required CI/CD pipelines to build, test and deploy the vehicle application as container image to the GitHub container registry|
```

2023-03-17 12:07 UTC, MP91 commented on content/en/docs/tutorials/prototyping/_index.md
> +|_/gen/vehicle\_model/_| if your prototype includes any exceptional API you added beforehand our [automated vehicle model lifecycle](/docs/tutorials/vehicle_model_creation/automated_model_lifecycle)
```suggestion
|_/gen/vehicle\_model/_| The generated model classes. If your prototype includes any exceptional API you added beforehand our [automated vehicle model lifecycle](/docs/tutorials/vehicle_model_creation/automated_model_lifecycle) takes care of handling the custom VSS vspec file coming from digital.auto and generates a vehicle_model when starting the devContainer |
```

2023-03-20 09:15 UTC, BjoernAtBosch approved these changes
LGTM

2023-03-20 09:25 UTC, MP91 approved these changes
LGTM

2023-03-20 15:55 UTC, doosuu approved these changes
LGTM

2023-03-21 08:08 UTC, merged