Documentation update
eclipse-velocitas/velocitas-docs pull request #99
Opened 2023-05-30 07:51 UTC by mml5bg

## Describe your changes

## Issue ticket number and link

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics?
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

2023-05-30 17:21 UTC, BjoernAtBosch reviewed
First chunk of comments

2023-05-30 17:21 UTC, BjoernAtBosch commented on content/en/docs/about/use_cases/_index.md
>  This Vehicle Apps are implemented on top of a Vehicle Model (which is generated from the underlying semantic models like VSS for a concrete programming language) and its underlying language-specific
```suggestion
Vehicle Apps are implemented on top of a Vehicle Model (which is generated from the underlying semantic models like VSS for a concrete programming language) and its underlying language-specific SDK to provide headless comfort functions or connected application functions like Seat Adjuster, Dog Mode, Trunk Delivery or Data Logging & triggering.
```
... or use "These" (plural)

2023-05-30 17:21 UTC, BjoernAtBosch commented on content/en/docs/concepts/development_model/_index.md
> +Next to a Vehicle App abstraction, the SDKs are [Middleware](#middleware-abstraction)-enabled, provide connectivity to the [Data Broker](#data-broker) and contain the ontology in the form of base cla
"Next to a Vehicle App abstraction, the SDKs are [Middleware](#middleware-abstraction)-enabled"
I don't understand the first part of the sentence

2023-05-30 17:21 UTC, BjoernAtBosch commented on content/en/docs/concepts/development_model/_index.md
> +  Vehicle Apps are released to cloud backends like [Pantaris](https://www.etas.com/en/products/pantaris-over-the-air-services.php) and can be updated in vehicles frequently over the air.
"released" or "uploaded"?
```suggestion
  Vehicle Apps are uploaded to cloud backends like [Pantaris](https://www.etas.com/en/products/pantaris-over-the-air-services.php) and can be updated in vehicles frequently over the air.
```

2023-05-30 17:21 UTC, BjoernAtBosch commented on content/en/docs/concepts/development_model/vehicle_app_sdk/_index.md
> +        super().**init**(parent)
Shouldn't that be handled by the Python tab??

2023-05-30 17:21 UTC, BjoernAtBosch commented on content/en/docs/tutorials/prototyping/service_integration.md
> +Our maintained [`devenv-runtimes`](https://github.com/eclipse-velocitas/devenv-runtimes) package ([Velocitas lifecycle management](/docs/concepts/lifecycle_management)) comes with the support of addi
```suggestion
Our maintained [`devenv-runtimes`](https://github.com/eclipse-velocitas/devenv-runtimes) package ([Velocitas lifecycle management](/docs/concepts/lifecycle_management)) comes with the support of adding further _Vehicle Services_ to the `runtime.json` of a package. More information [here](/docs/tutorials/vehicle-app-runtime/run_runtime_services_locally/#addchange-runtime-service-configuration). (A general vehicle _mock service_ is also coming soon!)

```

2023-05-30 17:21 UTC, BjoernAtBosch commented on content/en/docs/about/repository-overview/_index.md
> +| [devenv-runtimes](https://github.com/eclipse-velocitas/devenv-runtimes)           | Central configuration for maintained runtime executions                 |
```suggestion
| [devenv-runtimes](https://github.com/eclipse-velocitas/devenv-runtimes)                     | Central configuration for maintained runtime services         |
```

2023-05-31 11:21 UTC, dennismeister93 commented on content/en/docs/concepts/development_model/_index.md
> +Next to a Vehicle App abstraction, the SDKs are [Middleware](#middleware-abstraction)-enabled, provide connectivity to the [Data Broker](#data-broker) and contain the ontology in the form of base cla
Also hardly understandable for me to be honest.. :D

2023-05-31 11:23 UTC, dennismeister93 commented on content/en/docs/concepts/development_model/vehicle_app_sdk/_index.md
> +        super().**init**(parent)
What do you mean? Isn't it there?

2023-06-02 12:17 UTC, BjoernAtBosch reviewed
Further findings

2023-06-02 12:17 UTC, BjoernAtBosch commented on content/en/docs/concepts/development_model/_index.md
>  To reduce the effort required to implement [Vehicle Apps](#vehicle-apps), Velocitas provides a set of SDKs for different programming languages. SDKs are available for Python and C++, further SDKs for
```suggestion
Our SDKs, available for different programming languages, are the foundation for the vehicle abstraction provided by the vehicle model and the abstraction of the underlying middleware and communication protocols.
Besides that, they provide the base classes and utilities for the Vehicle Apps.
SDKs are available for Python and C++, currently. Further SDKs for Rust and C are planned.
```

2023-06-02 12:17 UTC, BjoernAtBosch commented on content/en/docs/concepts/development_model/_index.md
>  To reduce the effort required to implement [Vehicle Apps](#vehicle-apps), Velocitas provides a set of SDKs for different programming languages. SDKs are available for Python and C++, further SDKs for
"C": Really?

2023-06-02 12:17 UTC, BjoernAtBosch commented on content/en/docs/concepts/development_model/_index.md
> +Next to a Vehicle App abstraction, the SDKs are [Middleware](#middleware-abstraction)-enabled, provide connectivity to the [Data Broker](#data-broker) and contain the ontology in the form of base cla
Made a proposal above. This section could be removed then.

2023-06-02 12:22 UTC, BjoernAtBosch commented on content/en/docs/about/use_cases/_index.md
> +Vehicle Apps are implemented on top of a Vehicle Model (which is generated from the underlying semantic models like VSS for a concrete programming language) and its underlying language-specific SDK t
One could use their own model based on VSS "syntax" ...
(From my point of view we should clearer separate VSS in VSS "syntax" (or "rule set") and VSS "signal catalogue" to not alienate potential users.)

2023-06-08 11:31 UTC, kse3hi commented on content/en/docs/about/_index.md
We have section Concepts, and now we have paragraph "Concepts" on Line#59 that only contains links on next pages. Shall we rename it "What to have a look next?" ?

2023-06-08 14:15 UTC, kse3hi commented on content/en/docs/about/_index.md
Sometimes _Velocitas_ is cursive, sometime not. Please align a style.

2023-06-08 14:16 UTC, kse3hi commented on content/en/docs/about/_index.md
Same for _Vehicle App_ and _Vehicle Apps_

2023-06-08 14:36 UTC, BjoernAtBosch reviewed
Some comments

2023-06-08 14:36 UTC, BjoernAtBosch commented on content/en/docs/about/use_cases/seat_adjuster/_index.md
> +The _Seat Adjuster Vehicle App_ receives a MQTT message containing the seat position, which then triggers a seat adjustment command through the _Seat Service_ to change the seat position. Additionall
Hmh, here I think, we should remove the service mention. The fact that the seat position is adjusted by the seat service is of minor importance as it is "hidden" behind the data broker.
```suggestion
The _Seat Adjuster Vehicle App_ receives a MQTT message containing the desired seat position. Hereupon, it triggers a seat adjustment by sending a _set_ request with the desired position of the driver seat to the _Data Broker_. The Data Broker forwards this data to the _Seat Service_ to care for the actual seat adjustment.

Additionally, to ensure convenience for future trips, the car sharing company saves the driver's preferred seat position and utilizes it accordingly. _The Seat Adjuster Vehicle App_ subscribes to the seat position at the _Data Broker_ in order to receive updates of this data, streamed from the _Seat Service_ via the Data Broker.
```

2023-06-08 14:36 UTC, BjoernAtBosch commented on content/en/docs/concepts/deployment_model/vehicle_app_releases/_index.md
> +  The release workflow bundles all relevant images and artifacts into one tagged set of files and pushs it to the GitHub Container Registry. In addition, all the information needed for quality assura
```suggestion
  The release workflow bundles all relevant images and artifacts into one tagged set of files and pushes it to the GitHub Container Registry. In addition, all the information needed for quality assurance and documentation is published as release artifacts on GitHub. The image pushed to the GitHub Container Registry can be afterwards be deployed on your target system using the Over-The-Air (OTA) update system of your choice.
```

2023-06-08 14:36 UTC, BjoernAtBosch commented on content/en/docs/concepts/deployment_model/vehicle_app_releases/_index.md
> +The drawing below illustrates the different workflows, actions and artifacts that are automatically created for you. All workflows are intended as a sensible baseline and can be extended and adapted
It's genitive
```suggestion
The drawing below illustrates the different workflows, actions and artifacts that are automatically created for you. All workflows are intended as a sensible baseline and can be extended and adapted to the needs of your own project.
```

2023-06-08 14:36 UTC, BjoernAtBosch commented on content/en/docs/concepts/deployment_model/vehicle_app_releases/_index.md
> +- **Building a container for the app** - actions create a containerized version of the Vehicle App.
Shouldn't we mention, that it's multi targeted?
Also, "version" could be misleading. Better is "image" or "variant"
```suggestion
- **Building a container for the app** - actions create a containerized (mulit-target) image of the Vehicle App.
```

2023-06-08 14:36 UTC, BjoernAtBosch commented on content/en/docs/concepts/deployment_model/vehicle_app_releases/_index.md
> +GitHub Actions artifacts always have a retention period, which is 90 days by default. This may be configured differently in the specific GitHub organization. After this period, the QA info gets purge
```suggestion
GitHub Actions artifacts always have a retention period, which is 90 days by default. This may be configured differently in the specific GitHub organization. After this period, the QA info gets purged automatically. In this case, a re-run of the CI workflow would be required to regenerate all QA info needed for creating a release.
```

2023-06-08 14:36 UTC, BjoernAtBosch commented on content/en/docs/concepts/deployment_model/vehicle_app_releases/_index.md
> +Since that the registry does not have an automatic cleanup and keeps container images as long as they are not deleted. It is recommended that you automate the removal of older images to limit storage
```suggestion
Since the registry does not have an automatic cleanup, it keeps container images as long as they are not deleted. It is recommended that you automate the removal of older images to limit storage size and costs.
```

2023-06-08 14:36 UTC, BjoernAtBosch commented on content/en/docs/concepts/development_model/_index.md
> +Besides that, they provide the base classes and utilities for the Vehicle Apps.
Still too long and hard to understand ;-)
```suggestion
Our SDKs, available for different programming languages, are the foundation for the vehicle abstraction provided by the vehicle model. Furthermore, they offer abstraction from the underlying middleware and communication protocols, and they provide the base classes and utilities for the Vehicle Apps.
```

2023-06-09 11:06 UTC, MP91 commented on content/en/docs/tutorials/integration_tests.md
@mml5bg please add some details why we need to change the ports for the k3d execution

2023-06-09 11:11 UTC, MP91 requested changes

2023-06-09 11:11 UTC, MP91 commented on content/en/docs/tutorials/integration_tests.md
> +4. Re-run tests from the test runner.
Why is this even part of the integration tests? Thats is a general thing...

2023-06-09 11:11 UTC, MP91 commented on content/en/docs/tutorials/integration_tests.md
@mml5bg could you please rework this whole file? There are duplicates and there is no real story line

2023-06-13 12:04 UTC, MP91 requested changes

2023-06-13 12:04 UTC, MP91 commented on content/en/docs/tutorials/tutorial_how_to_deploy_a_vehicle_app_with_helm.md
@mml5bg please fix the last 2 bullet points of the preparation list, the scripts

Please add the correct command for the deployment

2023-06-13 12:04 UTC, MP91 commented on content/en/docs/tutorials/tutorial_how_to_deploy_a_vehicle_app_with_helm.md
> +This sample chart is generated by using the configuration of the [`runtime.json`](https://github.com/eclipse-velocitas/devenv-runtimes/blob/main/runtime.json) inside the [`devenv-runtimes`](https://g
This is not needed here

2023-06-13 12:04 UTC, MP91 commented on content/en/docs/tutorials/tutorial_how_to_deploy_a_vehicle_app_with_helm.md
but another prerequisite would be that the devcontainer is up and running

2023-06-14 06:49 UTC, MP91 commented on content/en/docs/concepts/deployment_model/vehicle_app_releases/_index.md
> +- **Building a container for the app** - actions create a containerized version of the Vehicle App.
The Ci workflow only produces a tar of the AMD64 image. I added the multi-architecture pipeline and changed the description accordingly. Please check again

2023-06-14 07:23 UTC, mml5bg commented on content/en/docs/tutorials/integration_tests.md
Done

2023-06-20 06:12 UTC, mml5bg commented on content/en/docs/tutorials/vehicle-app-development/tutorial_how_to_create_a_vehicle_app_python.md
> +### The following dapr configuration is part of the devenv-runtimes package (WIP: TBD)
What is the state here? Is this done, or not?

2023-06-20 06:45 UTC, MP91 commented on content/en/docs/tutorials/vehicle-app-development/tutorial_how_to_create_a_vehicle_app_python.md
> +### The following dapr configuration is part of the devenv-runtimes package (WIP: TBD)
I removed the dapr stuff in cpp since we don't really use dapr there but it is anyhow hidden in the runtime package...

@dennismeister93 you added this, what do you think?

2023-06-23 10:58 UTC, merged